### ISSUE TITLE
Please add a makefile

### ISSUE THREAD

**Issue by mkg20001** [kseistrup/filters#1]
Being able to `make install` those would be great

**Comment by kseistrup** [comment]
You are quite right. I appreciate the suggestion.

**Comment by mkg20001** [comment]
Btw, I packaged it for nix: https://github.com/mkg20001/nix/blob/master/pkgs/kseistrup-filters/default.nix

The install script could simply use wildcards to copy everything

Or it could be a bit more advanced and copy for ex sortc.sh into $(prefix)/bin/sortc directly

**Comment by kseistrup** [comment]
I have added a Makefile, please let me know if it does what you need. It installs to `/usr/local/{bin,man/man1}/` per default. If you want another location, say e.g. `make PREFIX=/usr install`.

I don't use makefiles as much as I should/could, so there's nothing fancy here.

May I ask you an unrelated question? I can see that you are removing the `-S` switch from the shebang line in the pure AWK script(s). How come?

If I were using the scripts at home, I would just put the absolute path of `awk`, `bash` and `sh`, and skip the `/usr/bin/env` thing altogether. Since I pushed these scripts to Microsoft Github, I thought I would add `/usr/bin/env` to make them easier for other people to use. In my understanding, the shebang line takes at most two arguments: the interpreter and one other argument. With `#!/usr/bin/env awk -f` we have three arguments, but a `-S` argument to `env` is supposed to split the following string. Now to my question: Does your `env` not support the `-S` switch?

**Comment by mkg20001** [comment]
The problem isn't the env binary. The problem is the patchShebangs script from nixpkgs (which turns the /usr/bin/env paths into version-specific paths) is not handling -S properly, which causes some errors. I've created an upstream issue https://github.com/NixOS/nixpkgs/issues/77539

**Comment by mkg20001** [comment]
Btw, your makefile is probably the most beautiful one I've ever seen. It does everything without any exceptions and I can fully understand it. This is art ^^

**Comment by kseistrup** [comment]
Thanks a lot for the kind words! :blush:

Oh, so the problem isn't `env`? I like if this catches a bug in NixOS' handling of shebang paths, but to be honest, I'd like to get rid of `env` altogether. The makefile should be able to handle it now, but I have only tested it on my own machine.

**Comment by kseistrup** [comment]
> I'd like to get rid of `env` altogether.

Because `-S` — although it seems to be the most correct solution — is unsupported on NetBSD and OpenBSD, as far as I can see. And even if they did support it, who says we can't find an OS that doesn't have `env` in `/usr/bin`.

**Comment by mkg20001** [comment]
In nix env is "the only way" since at runtime none of the usual paths (/usr/bin, /bin) work and at build time it needs to reference a fixed version of the binary otherwise there are problems, because it won't reference the exact version that was specified and the runtime behavior might differ from the behavior when it was tested.

The makefile replacement should work, since at build time all packages are in $PATH and it will dynamically find them

**Comment by kseistrup** [comment]
Oh my, that's an entirely new concept to me. I have a better picture now. Thanks!
